### ISSUE TITLE
I can't login to webmail using another domain to access nextcloud

### ISSUE THREAD

**Issue by Sollydus** [afterlogic/docker-webmail-lite#7]
I integrated Afterlogic Webmail with nextcloud and on nextcloud I'm using two different domains to access, when I try to login using the second domain I get the following Cookies error:
"Cookies are disabled in the browser. Please enable them for this web site and reload the page."
![Screenshot from 2022-03-28 09-13-51](https://user-images.githubusercontent.com/87372568/160395544-516a2fee-4ecc-4e00-a2cd-337c390f3883.png)

**Comment by afterlogic-support** [comment]
Looks like since recently Chrome blocks cookies within cross-domain IFrame unless they have SameSite attribute explicitly disabled. We plan to add a configuration option for that, meantime you can correct the behavior by modifying `statis/js/app.js` file. Locate the following code in it:

```javascript
return (document.cookie = [
		encode(key), '=', stringifyCookieValue(value),
		options.expires ? '; expires=' + options.expires.toUTCString() : '', // use expires attribute, max-age is not supported by IE
		options.path    ? '; path=' + options.path : '',
		options.domain  ? '; domain=' + options.domain : '',
		options.secure  ? '; secure' : ''
	].join(''));
```

and adjust it as follows:

```javascript
return (document.cookie = [
		encode(key), '=', stringifyCookieValue(value),
		options.expires ? '; expires=' + options.expires.toUTCString() : '', // use expires attribute, max-age is not supported by IE
		options.path    ? '; path=' + options.path : '',
		options.domain  ? '; domain=' + options.domain : '',
		options.secure  ? '; secure' : '',
		'; SameSite=None'
	].join(''));
```

You'll need to set "UseAppMinJs" to **false** in `data/settings/config.json` file for this to work (so that non-minified JavaScript is loaded instead of minified one), and clear browser cache to apply changes.

**Comment by Sollydus** [comment]
I made the change to but now the same error appears on both domains

**Comment by afterlogic-support** [comment]
Make sure the edit is done correctly and web browser cache is purged, that's the only suggestion I have.

**Comment by Sollydus** [comment]
**Note: I'm using post method**

My file static/js/app.js:
 ```js
 return (document.cookie = [
                                encode(key), '=', stringifyCookieValue(value),
                                options.expires ? '; expires=' + options.expires.toUTCString() : '', // u>
                                options.path    ? '; path=' + options.path : '',
                                options.domain  ? '; domain=' + options.domain : '',
                                options.secure  ? '; secure' : '',
                                '; SameSite=None'
                        ].join(''));
 ```
My file data/settings/config.json:
  ```js
     "UseAppMinJs": [
        false,
        "bool"
    ],
 ```

Then restarted apache2:
 ```bash
service apache2 restart
 ```
 
 Still with the same error

**Comment by afterlogic-support** [comment]
Try removing AuthToken cookie, by either logging out or deleting it from browser console, then log in again and see if that helps.

**Comment by afterlogic-support** [comment]
Issued closed due to inactivity. Feel free to reopen the issue, or open a new one, if the issue persists.

**Comment by afterlogic-support** [comment]
For those who found this thread and looking to resolve the similar issue: it seems setting `SameSite=None` will only work if `Secure` attribute is set - which in turn only happens if the installation is accessed over https. To make this work, you need to have both the external website and the WebMail installation accessed over https rather than http.
